datadog:
  datadog:
    apiKeyExistingSecret: "datadog-secret"
    appKeyExistingSecret: "datadog-secret-app"
    site: datadoghq.eu
    processAgent:
      enabled: true
    orchestratorExplorer:
      enabled: true
    kubelet:
      tlsVerify: false
    clusterName: minikubetest
    logs:
      enabled: true
      containerCollectAll: true